const always = { kind: 'always' };

export const stages = Object.freeze([
  {
    id: 'harness-tests',
    description: 'Prueba las reglas de estados, dependencias, trinquetes y artefactos del propio harness.',
    command: 'node --test quality/qa.test.mjs',
    required: true,
    dependencies: [],
    timeoutMs: 30000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/harness-tests.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'drift',
    description: 'Evita divergencia entre registro, comandos npm, documentos, reglas espejo y CI.',
    command: 'node quality/checks.mjs drift',
    required: true,
    dependencies: ['harness-tests'],
    timeoutMs: 30000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/drift.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'safe-change-policy',
    description: 'Bloquea nuevas supresiones, pruebas enfocadas o exclusiones que debiliten controles.',
    command: 'node quality/checks.mjs policy',
    required: true,
    dependencies: ['drift'],
    timeoutMs: 30000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/safe-change-policy.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'type-ratchet',
    description: 'Impide nuevos errores TypeScript por archivo y codigo estable.',
    command: 'node quality/checks.mjs type-ratchet',
    required: true,
    dependencies: ['safe-change-policy'],
    timeoutMs: 120000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/type-ratchet.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'lint-ratchet',
    description: 'Impide nuevas infracciones ESLint por archivo y regla sin tolerar ruido de carpetas ignoradas.',
    command: 'node quality/checks.mjs lint-ratchet',
    required: true,
    dependencies: ['safe-change-policy'],
    timeoutMs: 180000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/lint-ratchet.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'product-tests',
    description: 'Ejecuta las pruebas Vitest versionadas del CRM y aplica el trinquete por caso exacto.',
    command: 'node quality/checks.mjs test-ratchet',
    required: true,
    dependencies: ['safe-change-policy'],
    timeoutMs: 120000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/product-tests.log'],
    levels: ['quick', 'gate', 'release'],
  },
  {
    id: 'migration-static',
    description: 'Comprueba orden, identidad, RLS y protecciones estaticas de las migraciones versionadas.',
    command: 'node quality/checks.mjs migrations',
    required: true,
    dependencies: ['drift'],
    timeoutMs: 30000,
    condition: always,
    skipReason: '',
    artifacts: ['.tmp/qa-results/<run>/migration-static.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'e2e-chromium',
    description: 'Valida los tres harnesses de UI para cuentas y actividades en Chromium conservando trazas.',
    command: 'npx playwright test --config=playwright.e2e.config.ts --project=chromium',
    required: true,
    dependencies: ['product-tests'],
    timeoutMs: 180000,
    condition: always,
    skipReason: '',
    artifacts: ['playwright-report/', 'test-results/', '.tmp/qa-results/<run>/e2e-chromium.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'production-build',
    description: 'Empaqueta la PWA Next.js con el mismo comando usado para entrega.',
    command: 'npm run build',
    required: true,
    dependencies: ['type-ratchet', 'lint-ratchet', 'product-tests'],
    timeoutMs: 600000,
    condition: always,
    skipReason: '',
    artifacts: ['.next/', '.tmp/qa-results/<run>/production-build.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'pwa-offline-e2e',
    description: 'Instala la PWA construida, valida sus helpers y recarga el shell publico sin red.',
    command: 'npx playwright test --config=playwright.pwa.config.ts --project=chromium',
    required: true,
    dependencies: ['production-build'],
    timeoutMs: 300000,
    condition: always,
    skipReason: '',
    artifacts: ['playwright-report-pwa/', 'test-results-pwa/', '.tmp/qa-results/<run>/pwa-offline-e2e.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'database-replay',
    description: 'Reconstruye una base desechable y ejecuta contratos RLS con dos identidades.',
    command: 'node quality/checks.mjs database-replay',
    required: false,
    dependencies: ['migration-static'],
    timeoutMs: 300000,
    condition: {
      kind: 'env',
      name: 'QA_DATABASE_REPLAY_CONFIGURED',
      equals: '1',
      reason: 'No hay fuente estructural autoritativa ni base Supabase desechable configurada.',
      missingStatus: 'NOT_CONFIGURED',
    },
    skipReason: 'Requiere una base desechable; nunca usa produccion.',
    artifacts: ['.tmp/qa-results/<run>/database-replay.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'external-contracts',
    description: 'Reserva los contratos reales de Microsoft, Supabase y ForceManager para ejecucion autorizada.',
    command: 'node quality/checks.mjs external-contract-summary',
    required: false,
    dependencies: [],
    timeoutMs: 30000,
    condition: {
      kind: 'env',
      name: 'QA_ALLOW_EXTERNAL_CONTRACTS',
      equals: '1',
      reason: 'Contratos externos manuales no autorizados para este gate.',
      missingStatus: 'NOT_CONFIGURED',
    },
    skipReason: 'Fuera del gate determinista por depender de proveedores reales.',
    artifacts: ['.tmp/qa-results/<run>/external-contracts.log'],
    levels: ['gate', 'release'],
  },
  {
    id: 'diff-review',
    description: 'Exige confirmacion humana de que el diff no elimina ni debilita contratos.',
    command: 'node quality/checks.mjs confirmation QA_DIFF_REVIEWED',
    required: true,
    dependencies: ['production-build', 'e2e-chromium', 'pwa-offline-e2e'],
    timeoutMs: 10000,
    condition: {
      kind: 'env', name: 'QA_DIFF_REVIEWED', equals: '1',
      reason: 'Falta revision humana explicita del diff.', missingStatus: 'NOT_CONFIGURED',
    },
    skipReason: 'La aprobacion humana no se sustituye automaticamente.',
    artifacts: ['.tmp/qa-results/<run>/diff-review.log'],
    levels: ['release'],
  },
  {
    id: 'ci-review',
    description: 'Exige confirmar que el gate remoto correspondiente termino correctamente.',
    command: 'node quality/checks.mjs confirmation QA_CI_REVIEWED',
    required: true,
    dependencies: ['diff-review'],
    timeoutMs: 10000,
    condition: {
      kind: 'env', name: 'QA_CI_REVIEWED', equals: '1',
      reason: 'Falta revision del resultado real de CI.', missingStatus: 'NOT_CONFIGURED',
    },
    skipReason: 'CI no puede presumirse verde.',
    artifacts: ['.tmp/qa-results/<run>/ci-review.log'],
    levels: ['release'],
  },
  {
    id: 'human-approval',
    description: 'Exige aprobacion humana final antes de integrar o desplegar.',
    command: 'node quality/checks.mjs confirmation QA_HUMAN_APPROVED',
    required: true,
    dependencies: ['ci-review'],
    timeoutMs: 10000,
    condition: {
      kind: 'env', name: 'QA_HUMAN_APPROVED', equals: '1',
      reason: 'Falta aprobacion humana final.', missingStatus: 'NOT_CONFIGURED',
    },
    skipReason: 'La entrega nunca se autoaprueba.',
    artifacts: ['.tmp/qa-results/<run>/human-approval.log'],
    levels: ['release'],
  },
]);

export function stagesFor(level) {
  return stages.filter((stage) => stage.levels.includes(level));
}

export function renderRegistryMarkdown() {
  const header = '| ID | Nivel | Objetivo | Comando | Requerida | Timeout | Dependencias |';
  const divider = '|---|---|---|---|---:|---:|---|';
  const rows = stages.map((stage) => {
    const levels = stage.levels.join(', ');
    const deps = stage.dependencies.length ? stage.dependencies.join(', ') : '-';
    return `| ${stage.id} | ${levels} | ${stage.description} | \`${stage.command}\` | ${stage.required ? 'si' : 'no'} | ${stage.timeoutMs} ms | ${deps} |`;
  });
  return [header, divider, ...rows].join('\n');
}
