-- =============================================================================
-- SEED: SAP Item Groups for Commission Categories
-- Date: 2026-02-10
-- =============================================================================

INSERT INTO "CRM_ComisionCategorias" (prefijo, nombre) VALUES
('AMB01', 'Productos MR'),
('DES01', 'Desp material'),
('REC01', 'Material recup'),
('ASE01', 'Aseo'),
('TIN01', 'Bañera Firplak'),
('TIN02', 'Bañeras ECO'),
('TIN03', 'Bañera sin APR'),
('TIN04', 'Acc fabricados'),
('BAN01', 'Lavam FIRPLAK'),
('BAN02', 'Lavamanos ECO'),
('BAN03', 'Kit Lvm FIRPLA'),
('BAN04', 'Kit Lvm ECO'),
('BAN05', 'Muebles Lavam'),
('BAN06', 'Gabinetes baño'),
('BAN07', 'Pie de duchas'),
('BAN08', 'Cabinas ducha'),
('BAN09', 'Acce cab ducha'),
('COC01', 'Mueble cocina'),
('COC02', 'Alacenas'),
('COC03', 'Kit de cocinas'),
('COC04', 'Lavaplatos'),
('COC05', 'mesones ECO'),
('COC06', 'Electrodomest'),
('SID01', 'Dotacion y SI'),
('HPT04', 'Hidro ensamble'),
('EXH01', 'Elemento Exhib'),
('GRI01', 'Grif Importada'),
('GRI02', 'Grif DELTA Res'),
('GRI03', 'Grif Nacional'),
('GRI04', 'Grif DELTA Com'),
('HEM01', 'Hidros PREMIUM'),
('HEM02', 'Hidroaero PREM'),
('HEM03', 'Hidros CONSTRU'),
('HEM04', 'Hidroaero CONS'),
('HEM05', 'Hidros MULTIPE'),
('HEM06', 'Hidroaero MULT'),
('HPT01', 'Hidros OCEANO'),
('HPT02', 'HidroAero HSPA'),
('HPT03', 'Hidros FORMA'),
('HPT05', 'HidroaerSPAMUL'),
('IPR01', 'Otros Ind prod'),
('IPR02', 'Abrasivos'),
('MTO01', 'Rep Mantenim'),
('EMP01', 'Maderas'),
('EMP02', 'Material empaq'),
('MOL01', 'MP para moldes'),
('MOL02', 'Moldes producc'),
('MPD01', 'Gelco-pigm-res'),
('MPD02', 'Minerales'),
('MPD03', 'Fibra vidrio'),
('MPD04', 'Acces hidros'),
('MPD05', 'Decks'),
('OMP01', 'Otros Químicos'),
('OMP02', 'Tornillo-ferre'),
('OMP03', 'Pegantes'),
('OMP04', 'Otras m primas'),
('PAP01', 'Papel y utiles'),
('PAP02', 'Papeler ventas'),
('PLM01', 'Plomer coc-rop'),
('PLM02', 'Plomeria baños'),
('PLM03', 'Cajas y tapas'),
('EST01', 'Estruct secund'),
('GEL01', 'Gelco producid'),
('HUC01', 'Huacal armados'),
('INP01', 'Intermed Prodn'),
('PRD01', 'Subprod prodn'),
('REP01', 'Rep hidromasaj'),
('REP02', 'Repues muebles'),
('REP03', 'Repue griferia'),
('ROP01', 'LVR AQUA-const'),
('ROP02', 'Lavarropas ECO'),
('ROP03', 'Muebl lavarrop'),
('ROP04', 'Kit lavar AQUA'),
('ROP05', 'Kit lavar ECO'),
('INS01', 'Instalaciones'),
('INS02', 'Reparaciones'),
('INS03', 'Ases instalac'),
('CIV01', 'Canales ACO'),
('CIV02', 'zocalos'),
('CIV03', 'Ecovial'),
('ZCO01', 'Tiempos MO/CIF'),
('ZAF01', 'AF Maquinaria'),
('ZCC01', 'Conceptos cont'),
('BAN10', 'Sanitarios'),
('REV01', 'Mosaicos-paño'),
('REV02', 'Pisos-Paredes'),
('BAN11', 'Espejos'),
('ZNOPE', 'No Operacional'),
('ZAF02', 'AF Eq. Oficina'),
('ZAF03', 'AF Eq. Computo'),
('ZAF04', 'AF Eq. Comunic'),
('ZAF05', 'AF Redes'),
('MOL03', 'Modelos'),
('HPT06', 'Hidroaero OCEA'),
('HPT07', 'Hidro HSPA'),
('COC07', 'Meson Granito'),
('PER01', 'Cuidado Person'),
('HPT08', 'Hidroaero FORM'),
('HPT09', 'Hidro SPAMULTI'),
('ZAF06', 'AF Moldes'),
('BAN12', 'Mueb LVM Class'),
('BAN13', 'Kit Lvm CLASS'),
('PYM01', 'Prot muest com'),
('PYM02', 'Prot mues fabr'),
('SMC01', 'CocRop Lvm SMC'),
('PAP03', 'Muestra Colore'),
('ROP07', 'Muebl lvr Pro'),
('ROP06', 'LVR PRO'),
('BAN14', 'Piso ducha imp'),
('ROP08', 'Complem lvr'),
('ROP09', 'Kit Lvr PRO'),
('BAN15', 'BAN15-Mb LVMClassGol'),
('BAN16', 'BAN16-GabinetClassGo'),
('BAN17', 'Kit Lvm Gold'),
('MPD06', 'Maderas-Cantos'),
('MPD07', 'Herrajes Muebl'),
('EMP03', 'Mat Emp Mueble'),
('IPR03', 'Ind prod Muebl'),
('CIV04', 'Solu Hosp Inst'),
('GRI05', 'Kits Griferia'),
('BAN18', 'Kit Lvm Desinf'),
('BAN19', 'Sop lvm desinf'),
('MPD08', 'Mp solu desinf'),
('BAN20', 'Kit LvmIntelig'),
('MPD09', 'Piezas Muebles'),
('MTO02', 'Rep Mntto Mueb'),
('BAN21', 'KitClass Armad'),
('BAN22', 'MuebClass Arma'),
('BAN23', 'MuebLife Armad'),
('BAN24', 'MuebEssen Arma'),
('BAN26', 'KitLife Armad'),
('BAN27', 'Muebl Modu Ban'),
('EMP04', 'Empaq fabricad'),
('MPD10', 'Espejos mueble'),
('QUA01', 'Superf Quartzs'),
('QUA02', 'SupQuarzTrCoci'),
('COC08', 'Muebl ModuCoci'),
('ROP10', 'Mub Modu Lvr'),
('QUA03', 'SupQuarzTrBaño'),
('ACC01', 'Accesorios'),
('QUA04', 'Kit Lvm Qztn'),
('BAN25', 'KitEssen Arma'),
('CLO01', 'Closets Modul'),
('ROP11', 'MuebLVR Armad'),
('ROP12', 'MueLVR PRO Arm'),
('BAN28', 'LavamanoVessel'),
('BAN29', 'SuperfBañoMS'),
('BAN30', 'MuebAuxiliares'),
('ROP13', 'Kit Lvr Versa'),
('BAN31', 'SuperfMaderLvm'),
('COC09', 'MueblCociArmad'),
('BAN32', 'KitMblSinLvm'),
('BAN33', 'KitMbModular'),
('HCM01', 'CuidMntoHidro'),
('OUT01', 'ZOutdoorTurcoSauna'),
('OUT02', 'ZOutdoorAsadorAccesorios'),
('OUT03', 'ZOutdoor Mobiliario')
ON CONFLICT (prefijo) DO UPDATE SET nombre = EXCLUDED.nombre;
